### PR TITLE
Removed the quotes

### PR DESCRIPTION
**Pull request by yfu**
I actually tried quoting the entire key-value pair first and it did not work. :-)

### CODE REVIEW

**Comment by skoren** [comment]
The quotes should be OK, without them the grid options would be interpreted as only the partition but not the time request. You can see the submit command output by Canu to see if all the parameters were properly included. I've definitely run commands like:
```
canu -p asm -d asm genomeSize=50k -nanopore-raw pass.2d.fasta gridOptionsJobName=lamont "gridOptions=-A test"
```

**Comment by yfu** [comment]
I tried this specfile:

```
maxMemory=8
maxThreads=1
gridOptionsJobName=canu_ecoli

useGrid=1

# memory=64G
# thread=4

"gridOptions=-n 4 -q short -R rusage[mem=9000] -W 0:20 -R span[hosts=1]"
```

And it throws out this error. It seems to get confused with the second quote? It might be a LSF-specific thing, though.

```
-- Starting command on Mon Jun 13 16:52:11 2016 with 2214 GB free disk space

      bsub \
        -n 4 -q short -R rusage[mem=9000] -W 0:20 -R span[hosts=1]"  -M 4096 -n 1 \
        -J "meryl_ecoli_canu_ecoli[1-1]" \
         \
        -o /home/yf60w/data/cl/results/2016-06-11-canu/ecoli_test/ecoli-auto/correction/0-mercounts/meryl.%I.out \
        /home/yf60w/data/cl/results/2016-06-11-canu/ecoli_test/ecoli-auto/correction/0-mercounts/meryl.sh
    
sh: -c: line 2: unexpected EOF while looking for matching `"'
sh: -c: line 6: syntax error: unexpected end of file
```

If I use the following specfile, it works:

```
maxMemory=8
maxThreads=1
gridOptionsJobName=canu_ecoli

useGrid=1

# memory=64G                                                                                                                                                                    
# thread=4                                                                                                                                                                      

gridOptions=-n 4 -q short -R rusage[mem=9000] -W 0:20 -R span[hosts=1]
```

**Comment by skoren** [comment]
Ah, in the spec file you don't want quotes, only on the command line, we should clarify that in the docs.

**Comment by yfu** [comment]
Oops! Sorry that I misunderstood that!

**Pull request closed without merging**
