### PR TITLE
`set -eu` in the emitted shell scripts

### PR DESCRIPTION
**Pull request by SHuang-Broad**
Minor

### CODE REVIEW

**Comment by SHuang-Broad** [comment]
closing because some of the meta-generated code will cause the script to exit with `set -eu`.
Though it would be good if this is turned on in the (near) future, since it prevents the "continue on error" behavior.

**Comment by brianwalenz** [comment]
Do you remember which pieces were failing with -e?  We're not using the return codes from scripts, instead relying on checking if outputs exist.  You'll find a lot of patterns like `command ... > output.WORKING && mv output.WORKING output`.  If 'output' is needed later in that same script, it should be guarded with `if [ -e output ] ; then`.

**Comment by SHuang-Broad** [comment]
Yes, the error was in the part of shell code that is generated by [this line](https://github.com/marbl/canu/blob/c64bf88508525cf4d74ab27092214bbea2b212b7/src/pipelines/canu/Execution.pm#L360).

The error message is `CANU_LOCAL_JOB_ID is unset`.

**Comment by SHuang-Broad** [comment]
There could be more meta-generated code that is going to trigger errors with `set -eu`, this is just one example.

**Pull request closed without merging**
